# 💖 Sponsors and Backers

# KoBar is an open-source project. If you find this utility sidebar helpful, consider supporting its ongoing development!

ko_fi: eedali
custom: Paypal | https://www.paypal.me/ekremedali
Bitcoin: bc1q8ewl8la7rnkq3p68cj0hznwtqxxt8ddh35jyps
Ethereum: 0x55AF8F731D320DF65b7987566954b9808CBA0a71
BSC: 0x55AF8F731D320DF65b7987566954b9808CBA0a71
Solana: 4fw24ZETeKgXjMSaHgpfS519BdQcjVPACkVsZ8R7kett
